# Generated by Django 4.2.2 on 2023-06-18 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_clientes_ano_remove_clientes_marca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Limpeza', 'Limpeza'), ('Manutenção', 'Manutenção'), ('Funilaria', 'Funilaria'), ('Diagnóstico', 'Diagnóstico'), ('Alinhamento', 'Alinhamento'), ('Troca de Pneu', 'Troca de Pneu'), ('Outro', 'Outro')], max_length=55)),
                ('descricao', models.CharField(max_length=80)),
                ('cliente', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_cliente', to='clientes.clientes')),
                ('servCar', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serv_car', to='clientes.carro')),
            ],
        ),
    ]
