# Generated by Django 4.2.2 on 2023-06-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_servicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em Andamento', 'Em Andamento'), ('Concluido', 'Concluido')], default='Pendente', max_length=55),
        ),
    ]
